spring.main.banner-mode=off
logging.level.root=ERROR
# Cho healthcheck
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
