server.port=8082
server.forward-headers-strategy=framework
api.base-path=/api/v1

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.clean-disabled=true
spring.flyway.validate-on-migrate=true

security.jwt.secret=${JWT_SECRET}
security.jwt.previous-secret=${JWT_PREVIOUS_SECRET:}
security.jwt.expiration-minutes=${JWT_EXP_MINUTES}
management.server.port=${MANAGEMENT_SERVER_PORT:9082}
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
logging.level.root=ERROR
