# --- Server
server.port=8082

# --- DB (ví d? Postgres; s?a user/pass/db ?úng môi tr??ng c?a b?n)
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service
spring.datasource.username=postgres
spring.datasource.password=d433221dat
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===== JWT =====
security.jwt.secret=w5h2Yk1Gd3dtdkFzT0h0bTFwM05XUnJvV0V1NHVZbU5yZFRyWW9oUUNmQ1hLcw==

# N?u code v?n @Value("${JWT_SECRET}") thì b?c c?u:
JWT_SECRET=${security.jwt.secret}

# ===== Base path =====
api.base-path=/api/v1
