# gi?ng c?
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
logging.level.root=ERROR

JWT_SECRET=w5h2Yk1Gd3dtdkFzT0h0bTFwM05XUnJvV0V1NHVZbU5yZFRyWW9oUUNmQ1hLcw==
JWT_EXP_MINUTES=120

spring.test.database.replace=NONE

# JPA cho test (tùy em, ?? c?ng ???c)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
