# ===== Server =====
server.port=8082

# ===== PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service
spring.datasource.username=postgres
spring.datasource.password=d433221dat
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== JWT (ph?i trùng v?i auth-service) =====
security.jwt.secret=w5h2Yk1Gd3dtdkFzT0h0bTFwM05XUnJvV0V1NHVZbU5yZFRyWW9oUUNmQ1hLcw==
security.jwt.expiration-minutes=120

# Base path
api.base-path=/api/v1
