spring.application.name=core
#security.jwt.secret=${JWT_SECRET}
#security.jwt.expiration-minutes=${JWT_EXP_MINUTES:1440}
# ===== JWT =====
security.jwt.secret=w5h2Yk1Gd3dtdkFzT0h0bTFwM05XUnJvV0V1NHVZbU5yZFRyWW9oUUNmQ1hLcw==
security.jwt.expiration-minutes=120